-- Create features table
CREATE TABLE features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT NOT NULL,
    order_no INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Insert default features
INSERT INTO features (title, description, icon_name, order_no) VALUES
    ('Hızlı Teslimat', 'Eşyalarınızı güvenle ve zamanında teslim ediyoruz', 'TbTruckDelivery', 1),
    ('7/24 Destek', 'Müşteri hizmetlerimiz her zaman yanınızda', 'MdSupportAgent', 2),
    ('Güvenli Taşıma', 'Eşyalarınız sigortalı ve güvende', 'MdSecurity', 3),
    ('Profesyonel Paketleme', 'Uzman ekibimizle profesyonel paketleme hizmeti', 'FaBoxOpen', 4);

-- Enable RLS
ALTER TABLE features ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON features
    FOR SELECT USING (true);

CREATE POLICY "Enable all access for service role" ON features
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role'); 